# Generated by agentseam 0.1.1 -- bundle("cursor"). Do not hand-edit, except the
# HANDLER block below (between "agentseam handler >>>" and "<<< agentseam handler"),
# which is exactly what this file leaves for you to fill in.
#
# Self-contained: stdlib only, no "import agentseam" anywhere in this file. Regenerate
# with `agentseam.bundler.bundle("cursor")` (same agentseam version -> identical bytes,
# except your own edits inside the handler block) rather than patching this by hand.
# https://github.com/open-coder-ai/agentseam

from __future__ import annotations

import json
_json = json
import sys

import os as _chock_os
import shlex as _chock_shlex
import subprocess as _chock_subprocess
from datetime import datetime as _chock_datetime, timezone as _chock_timezone
from pathlib import Path as _chock_Path

# ------------------------------------------------------------------------------
# contract (agentseam 0.1.1)

"""Canonical event vocabulary, normalized envelope, and decision type.

This is L0: the contract every adapter speaks. Nothing here knows any vendor.
Stdlib only — this module is embedded verbatim into rendered single-file adapters.
"""



# --- canonical lifecycle events -------------------------------------------------
# Vendor event names map ONTO these; adapters own the mapping. A vendor that lacks
# an event simply has no row for it in the capability matrix — that absence is the
# honest coverage floor, not something to paper over.
SESSION_START = "session_start"
SESSION_END = "session_end"
PROMPT_SUBMIT = "prompt_submit"
PRE_TOOL = "pre_tool"
POST_TOOL = "post_tool"
TOOL_FAILURE = "tool_failure"
PRE_COMPACT = "pre_compact"
STOP = "stop"
SUBAGENT_START = "subagent_start"
SUBAGENT_STOP = "subagent_stop"
INSTRUCTIONS_LOADED = "instructions_loaded"
FILE_CHANGED = "file_changed"

#: Not a lifecycle event: the honest answer when a vendor sends something this adapter has
#: no mapping for. Deliberately outside EVENTS, so a handler matching on the vocabulary can
#: never match it by accident.
#:
#: The alternative was what several adapters used to do -- fall back to the nearest
#: canonical event -- which reports an unknown event as `pre_tool` and invites a guardrail
#: to evaluate a pre-tool policy against something that is not one. New vendor events appear
#: without warning; being told is the only safe outcome.
UNKNOWN = "unknown"

EVENTS = (
    SESSION_START,
    SESSION_END,
    PROMPT_SUBMIT,
    PRE_TOOL,
    POST_TOOL,
    TOOL_FAILURE,
    PRE_COMPACT,
    STOP,
    SUBAGENT_START,
    SUBAGENT_STOP,
    INSTRUCTIONS_LOADED,
    FILE_CHANGED,
)

# --- normalized envelope --------------------------------------------------------


class Event:
    """One agent lifecycle event, normalized.

    `raw` is always kept: adapters normalize the fields consumers usually want, and
    a consumer that needs something vendor-specific can still reach it rather than
    being blocked by our vocabulary.
    """

    __slots__ = (
        "agent",
        "event",
        "tool",
        "command",
        "path",
        "content",
        "output",
        "prompt",
        "session_id",
        "tool_use_id",
        "cwd",
        "raw",
    )

    def __init__(
        self,
        agent,
        event,
        *,
        tool=None,
        command=None,
        path=None,
        content=None,
        output=None,
        prompt=None,
        session_id=None,
        tool_use_id=None,
        cwd=None,
        raw=None,
    ):
        self.agent = agent
        self.event = event
        self.tool = tool
        self.command = command  # shell command, when the tool carries one
        self.path = path  # target file, when the tool writes one
        self.content = content  # file text being written (pre_tool on write tools)
        self.output = output  # tool result (post_tool)
        self.prompt = prompt  # user prompt text (prompt_submit)
        self.session_id = session_id
        self.tool_use_id = tool_use_id
        self.cwd = cwd
        self.raw = raw if raw is not None else {}

    def __repr__(self):  # pragma: no cover - debugging aid
        return "Event(%s/%s tool=%r path=%r)" % (self.agent, self.event, self.tool, self.path)


# --- decisions ------------------------------------------------------------------

ALLOW = "allow"
DENY = "deny"
ASK = "ask"
REWRITE = "rewrite"
#: "I actively approve -- skip the user's own confirmation," never the default. ALLOW means
#: no objection; a bare ALLOW that spoke this loudly was the exact defect
#: allow_semantics.py exists to audit. VOUCH is that same loud word, used on purpose, on the
#: vendors it is established to mean this. See dispatch.degrade() and
#: allow_semantics.VOUCH_SPEAKS for which those are, and how everyone else degrades.
VOUCH = "vouch"


class Decision:
    """What a handler wants to happen. Adapters translate this to vendor dialect.

    `evidence` is an optional payload-free dict a consumer can carry through to its
    own log; agentseam never writes it anywhere itself.

    `context` is different: free text meant to reach the MODEL, on the few vendor
    surfaces that take side-channel context injection independent of the outcome
    (Claude Code's hookSpecificOutput.additionalContext at SessionStart and
    UserPromptSubmit today). An adapter with no such surface drops it silently --
    the same honest-degrade shape as an unsupported outcome, not a promise every
    vendor can keep. It is advisory content, never a substitute for `reason`, which
    still speaks to the vendor's own decision/refusal dialect.
    """

    __slots__ = ("outcome", "reason", "updated_input", "evidence", "context")

    def __init__(self, outcome, reason=None, updated_input=None, evidence=None, context=None):
        if outcome not in (ALLOW, DENY, ASK, REWRITE, VOUCH):
            raise ValueError("unknown outcome: %r" % (outcome,))
        self.outcome = outcome
        self.reason = reason
        self.updated_input = updated_input
        self.evidence = evidence or {}
        self.context = context

    # constructors read better at call sites than Decision("deny", ...)
    @classmethod
    def allow(cls, reason=None, evidence=None, context=None):
        return cls(ALLOW, reason, evidence=evidence, context=context)

    @classmethod
    def deny(cls, reason, evidence=None, context=None):
        return cls(DENY, reason, evidence=evidence, context=context)

    @classmethod
    def ask(cls, reason, evidence=None, context=None):
        return cls(ASK, reason, evidence=evidence, context=context)

    @classmethod
    def rewrite(cls, updated_input, reason=None, evidence=None, context=None):
        return cls(REWRITE, reason, updated_input=updated_input, evidence=evidence, context=context)

    @classmethod
    def vouch(cls, reason=None, evidence=None, context=None):
        return cls(VOUCH, reason, evidence=evidence, context=context)

    def __repr__(self):  # pragma: no cover - debugging aid
        return "Decision(%s, %r)" % (self.outcome, self.reason)


def degraded_from(decision):
    """What this decision was before the dispatcher reduced it, or None.

    An adapter explaining why an outcome changed shape has to read this, not the outcome
    it was handed. A rewrite reduced to `ask` and then blocked by an agent that cannot
    prompt would otherwise be reported as a confirmation request that failed -- and it was
    never a confirmation request.
    """
    return (decision.evidence or {}).get("degraded_from")


def tool_input_of(raw):
    """The tool's arguments as a dict, decoding the JSON-string form some vendors send.

    `tool_input` is whatever the agent chose to serialise, and it is not always an object.
    Witnessed live on VS Code Copilot (2026-08-29), same adapter and same `Edit` tool, in
    two runs routed to different models: once as an object with path/old_str/new_str, once
    as a 129-character JSON *string*. Both are the vendor's real wire format.

    That difference is not cosmetic. Against the object the parser reports the file and the
    content; against the string it reported neither, so a policy denying on secret content
    saw an empty write and allowed it. The adapters guarded the string case against a crash
    (a crash is an allow) but resolved it to `{}`, which is a quieter version of the same
    outcome: the guard is blind and says nothing about it.

    Decoding is not a guess about an unrecorded shape -- a string that parses to a JSON
    object IS that object, and the alternative is discarding data the vendor sent. Only a
    dict counts: a JSON list or scalar is not a set of tool arguments, and `{}` remains the
    honest answer for anything that does not parse.
    """
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, str) and raw[:1] == "{":
        try:
            parsed = _json.loads(raw)
        except Exception:
            return {}
        if isinstance(parsed, dict):
            return parsed
    return {}


# ------------------------------------------------------------------------------
# cursor adapter

"""Cursor adapter.

Cursor exposes three separate hook surfaces, and keeping them apart is the point:

  * **Agent hooks** fire during Cmd+K / Agent Chat. `preToolUse` is generic -- it fires for
    *every* tool (Shell, Read, Write, MCP, Task) -- and its response carries `updated_input`,
    so this is a genuine block-and-rewrite gate, including on file writes.
  * **Tab hooks** fire for inline completions only, so a policy can treat autonomous Tab edits
    differently from user-directed agent work.
  * **App lifecycle** (`workspaceOpen`) fires outside any session and has no canonical event here;
    it is left unmapped rather than bent into one that means something else.

Three vendor facts shape the response code, and each one costs something if ignored:

  * `ask` is accepted by the `preToolUse` schema **but not enforced today**. Returning it
    there would read as a prompt and behave as a pass, so we deny instead and say why.
    On `beforeShellExecution` / `beforeMCPExecution` an `ask` is honoured.
  * `afterFileEdit` supports **no output fields at all**, and the write has already landed.
    A deny there can only be recorded.
  * Hooks fail **open** by default; `failClosed: true` per hook definition makes them fail closed,
    so enforcement level here is a configuration choice, not a fixed property.

Verified against Cursor's own hooks documentation (2026-08-26).
"""




AGENT = "cursor"

EVENT_MAP = {
    # agent surface
    "sessionStart": SESSION_START,
    "sessionEnd": SESSION_END,
    "preToolUse": PRE_TOOL,
    "postToolUse": POST_TOOL,
    "postToolUseFailure": TOOL_FAILURE,
    "subagentStart": SUBAGENT_START,
    "subagentStop": SUBAGENT_STOP,
    "beforeShellExecution": PRE_TOOL,
    "afterShellExecution": POST_TOOL,
    "beforeMCPExecution": PRE_TOOL,
    "afterMCPExecution": POST_TOOL,
    "beforeReadFile": PRE_TOOL,
    "afterFileEdit": FILE_CHANGED,
    "beforeSubmitPrompt": PROMPT_SUBMIT,
    "preCompact": PRE_COMPACT,
    "stop": STOP,
    # tab surface -- same canonical events, distinguishable by `event.tool`
    "beforeTabFileRead": PRE_TOOL,
    "afterTabFileEdit": FILE_CHANGED,
}

#: Gates answering `{"permission": ...}`; the value says whether `ask` is honoured.
_PERMISSION_GATES = {
    "preToolUse": False,  # schema accepts "ask"; Cursor does not enforce it today
    "beforeShellExecution": True,
    "beforeMCPExecution": True,
    "beforeReadFile": False,  # allow/deny only
    "beforeTabFileRead": False,
}

#: Every event where a decision is expected -- NOT the set above (which dialect a gate
#: speaks). Reusing that left beforeSubmitPrompt, which speaks `continue` rather than
#: `permission`, installed fail-OPEN: Cursor's default.
_GATES = frozenset(_PERMISSION_GATES) | {"beforeSubmitPrompt"}

#: Post-hoc events: the action already happened, so nothing we return prevents it.
#: postToolUseFailure was missing here, so a deny at a failed tool call returned silence instead of the additional_context record every other post-hoc event gets.
_POST_HOC = (
    "postToolUse",
    "postToolUseFailure",
    "afterShellExecution",
    "afterMCPExecution",
    "afterFileEdit",
    "afterTabFileEdit",
)

#: No output contract at all -- returning JSON here is ignored.
_MUTE = ("afterFileEdit", "afterTabFileEdit")


#: Cursor's base schema fields, used as positive ID where the event name is not enough.
_CURSOR_MARKERS = ("conversation_id", "generation_id", "cursor_version", "workspace_roots")

#: Event names Cursor shares with OpenAI Codex CLI, which also spells its events in
#: camelCase. On these the name proves nothing, so a Cursor marker must be present, or both
#: adapters claim the payload, detection goes ambiguous, and the dispatcher allows the call.
_AMBIGUOUS_NAMES = (
    "preToolUse",
    "postToolUse",
    "sessionStart",
    "sessionEnd",
    "preCompact",
    "stop",
    "subagentStart",
    "subagentStop",
)


def claims(raw):
    """True when this payload looks like Cursor's shape."""
    if not isinstance(raw, dict):
        return False
    name = raw.get("hook_event_name")
    if name in EVENT_MAP:
        if name in _AMBIGUOUS_NAMES:
            return any(k in raw for k in _CURSOR_MARKERS)
        return True
    # Cursor does not always name the event. These shapes are unambiguous:
    # beforeShellExecution puts `command` at the top level beside cwd/sandbox.
    if isinstance(raw.get("command"), str) and ("sandbox" in raw or "cwd" in raw) and "tool_input" not in raw:
        return True
    # afterFileEdit: file_path + edits[], with no tool_name wrapper.
    return "file_path" in raw and isinstance(raw.get("edits"), list) and "tool_name" not in raw


def _content_of(raw):
    edits = raw.get("edits")
    if isinstance(edits, list):
        return "\n".join(str(e.get("new_string", "")) for e in edits) or None
    ti = raw.get("tool_input")
    if isinstance(ti, dict):
        return ti.get("content") or ti.get("new_string") or None
    # The read gates put the file's text at the TOP level -- the asymmetry `path` handles
    # below. Last in the chain, so nothing carrying content elsewhere moves.
    content = raw.get("content")
    return content if isinstance(content, str) and content else None


def parse(raw):
    name = raw.get("hook_event_name")
    if name is None:
        # Cursor does not always name the event, so shape decides -- but only when there is
        # no name. A name we do not recognise is a new event, and guessing at one is how an
        # unknown event gets reported as the gate.
        name = "afterFileEdit" if isinstance(raw.get("edits"), list) else "beforeShellExecution"
    ti = raw.get("tool_input")
    ti = tool_input_of(ti)
    command = raw.get("command") or ti.get("command")
    # preToolUse nests the target inside tool_input; the file-scoped hooks put it at the
    # top level. Reading only one of the two leaves a guardrail asking "which file?" with
    # no answer on exactly the gate that could still stop the write.
    path = raw.get("file_path") or ti.get("file_path") or ti.get("path")
    return Event(
        AGENT,
        # An event this adapter has no mapping for resolves to UNKNOWN, never to the
        # nearest canonical one: relabelling it invites a guardrail to evaluate the wrong policy against it.
        EVENT_MAP.get(name, UNKNOWN),
        tool=raw.get("tool_name") or name,
        command=command,
        path=path,
        content=_content_of(raw),
        output=raw.get("tool_output") or raw.get("output") or raw.get("result_json"),
        prompt=raw.get("prompt"),
        session_id=raw.get("conversation_id"),
        tool_use_id=raw.get("tool_use_id"),
        cwd=raw.get("cwd"),
        raw=raw,
    )


def _because(reason, note):
    """Keep the handler's own reason and add why the outcome changed shape.

    Replacing it would tell the user their rewrite was refused for wanting confirmation,
    which is a different and untrue story.
    """
    return "%s (%s)" % (reason, note) if reason else note


def _vendor_event(event):
    """The vendor event name, which `parse` keeps in `tool` when the tool has no name."""
    name = (event.raw or {}).get("hook_event_name")
    return name if name in EVENT_MAP else (event.tool if event.tool in EVENT_MAP else "beforeShellExecution")


#: Decision words this vendor accepts. preToolUse's schema takes "ask" but does not enforce it, so respond() denies there instead.
DECISION_VOCABULARY = frozenset({"allow", "deny", "ask"})


def respond(decision, event):
    name = _vendor_event(event)

    if name in _MUTE:
        # Documented as supporting no output fields. Exit 0 and let the caller's own log
        # carry the finding -- pretending otherwise would invent a gate that isn't there.
        return "", 0

    if name in _POST_HOC:
        if decision.outcome in (DENY, ASK):
            note = "observed after the fact (%s cannot prevent it): %s" % (name, decision.reason or "policy violation")
            return _json.dumps({"additional_context": note}), 0
        return "", 0

    if name == "beforeSubmitPrompt":
        # This gate speaks `continue`, not `permission`.
        payload = {"continue": decision.outcome not in (DENY, ASK, REWRITE)}
        if decision.reason:
            payload["user_message"] = decision.reason
        return _json.dumps(payload), 0

    if name not in _PERMISSION_GATES:
        # sessionStart, stop, preCompact and friends: observation only.
        return "", 0

    honours_ask = _PERMISSION_GATES[name]
    payload = {}
    reason = decision.reason

    if decision.outcome == REWRITE:
        if name == "preToolUse" and decision.updated_input is not None:
            payload = {"permission": "allow", "updated_input": decision.updated_input}
        else:
            # Only preToolUse carries updated_input. Elsewhere a rewrite has no expression,
            # and allowing the *unmodified* input through would be the dangerous reading.
            payload = {"permission": "deny"}
            reason = _because(reason, "input requires modification, which this gate cannot express")
    elif decision.outcome == DENY:
        payload = {"permission": "deny"}
    elif decision.outcome == ASK:
        if honours_ask:
            payload = {"permission": "ask"}
        else:
            payload = {"permission": "deny"}
            note = (
                "%s cannot modify a tool call" % name
                if degraded_from(decision) == REWRITE
                else "%s cannot prompt for confirmation" % name
            )
            reason = _because(reason, "%s, so this is a block" % note)
    else:
        payload = {"permission": "allow"}

    if reason and payload.get("permission") != "allow":
        payload["user_message"] = reason
        payload["agent_message"] = reason
    return _json.dumps(payload), 0


#: Canonical event -> the vendor event that gates it most tightly. `pre_tool` maps to the
#: generic `preToolUse` rather than `beforeShellExecution`: it covers every tool, not just
#: shell, and it is the only one that can rewrite.
REVERSE_EVENT_MAP = {
    PRE_TOOL: "preToolUse",
    POST_TOOL: "postToolUse",
    TOOL_FAILURE: "postToolUseFailure",
    PROMPT_SUBMIT: "beforeSubmitPrompt",
    SESSION_START: "sessionStart",
    SESSION_END: "sessionEnd",
    SUBAGENT_START: "subagentStart",
    SUBAGENT_STOP: "subagentStop",
    STOP: "stop",
    PRE_COMPACT: "preCompact",
    FILE_CHANGED: "afterFileEdit",
}


def hook_config(canonical_events, command, matcher=None, fail_closed=True):
    hooks = {}
    for ev in canonical_events:
        name = REVERSE_EVENT_MAP.get(ev)
        if not name:
            continue
        entry = {"command": command}
        # No matcher is written: Cursor's means different things per event (a COMMAND-TEXT regex
        # at beforeShellExecution) and preToolUse's is unestablished. A wrong matcher matches
        # nothing while the install still reports success. See this row's matrix note.
        # Fail open on a gate and a crashed hook silently permits the thing it was
        # installed to stop, so ask for fail-closed wherever a decision is expected.
        # fail_closed=False marks an observer (the capture probe): wired as a gate it would block the user's command whenever it cannot launch.
        if fail_closed and name in _GATES:
            entry["failClosed"] = True
        hooks.setdefault(name, []).append(entry)
    return {"version": 1, "hooks": hooks}


CONFIG_PATH = ".cursor/hooks.json"


# ------------------------------------------------------------------------------
# runtime (agentseam dispatch, specialized to cursor)

_VOUCH_SPEAKS = False
_REWRITE_EVENTS = frozenset(('pre_tool',))


def degrade(decision, event):
    """Reduce a decision to what 'cursor' can actually honor, honestly.

    This is agentseam.dispatch.degrade(), specialized to one fixed agent so this file needs
    no "import agentseam" -- no evidence establishes that an explicit approval word means anything beyond a plain allow here, so vouch degrades to one; see agentseam.allow_semantics.
    """
    if decision.outcome == REWRITE and event.event not in _REWRITE_EVENTS:
        evidence = dict(decision.evidence)
        evidence["degraded_from"] = REWRITE
        return Decision.ask(decision.reason or "input requires modification before it can run", evidence=evidence)
    if decision.outcome == VOUCH and not _VOUCH_SPEAKS:
        evidence = dict(decision.evidence)
        evidence["degraded_from"] = VOUCH
        return Decision.allow(decision.reason, evidence=evidence, context=decision.context)
    return decision


# >>> agentseam handler >>>
GUARD_VIOLATION = 1

_BASH_CANDIDATES = ('bash', 'C:\\Program Files\\Git\\usr\\bin\\bash.exe', 'C:\\Program Files\\Git\\bin\\bash.exe', 'C:\\Program Files (x86)\\Git\\usr\\bin\\bash.exe', '/bin/bash', '/usr/bin/bash')

GATE_LOG_ENV = 'CHOCK_GATE_LOG'

_LOG_MAX_BYTES = 1048576

_GUARD_TIMEOUT_SECONDS = 30

def guard_path_from_argv(argv: list[str]) -> _chock_Path | None:
    """The `--guard <path>` argument a vendored runtime was invoked with, or None.

    Read straight off argv rather than through argparse: every event a vendored runtime is
    ever invoked for goes through the same command line, chosen at install time
    (`hooks/*_install.py`), so there is nothing else on it to parse.
    """
    if '--guard' in argv:
        i = argv.index('--guard')
        if i + 1 < len(argv):
            return _chock_Path(argv[i + 1])
    return None

def find_bash(guard: _chock_Path) -> str | None:
    """First interpreter that can actually see `guard`, or None.

    The probe runs `test -f <guard>` rather than `--version`: the question is not whether
    a bash exists but whether *this* bash can resolve the path we are about to hand it.
    """
    for candidate in _BASH_CANDIDATES:
        try:
            proc = _chock_subprocess.run([candidate, '-c', f'test -f "{guard.as_posix()}"'], capture_output=True, timeout=10)
        except (OSError, _chock_subprocess.SubprocessError):
            continue
        if proc.returncode == 0:
            return candidate
    return None

def run_guard(guard: _chock_Path, command: str) -> bool | None:
    """True when the guard ran and reported a violation, False when it ran clean.

    None means the check did not happen -- unparseable command, no usable bash, a crash.
    That is distinct from False and must stay distinct: every "not checked" path still
    allows, so folding it into False changes no verdict, but it would let the outcome log
    record a passing guard for a check that never ran.

    Nothing here blocks on its own failure. Treating "could not run" as a violation would
    stop every Bash call the moment bash was missing -- turning a best-effort guard into a
    total outage. Failing open is stated loudly on stderr instead of silently.
    """
    try:
        args = _chock_shlex.split(command)
    except ValueError:
        print('chock: could not parse command (unbalanced quotes), not checked', file=sys.stderr)
        return None
    if not args:
        return None
    bash = find_bash(guard)
    if bash is None:
        print(f'chock: no usable bash found, {guard.name} not checked', file=sys.stderr)
        return None
    try:
        env = {**_chock_os.environ, 'CHOCK_RAW_COMMAND': command}
        proc = _chock_subprocess.run([bash, str(guard), *args], capture_output=True, text=True, encoding='utf-8', errors='replace', env=env, timeout=_GUARD_TIMEOUT_SECONDS)
    except (OSError, UnicodeError, _chock_subprocess.TimeoutExpired) as exc:
        print(f'chock: guard could not run, not checked: {exc}', file=sys.stderr)
        return None
    if proc.returncode == GUARD_VIOLATION:
        sys.stderr.write(proc.stdout or '')
        sys.stderr.write(proc.stderr or '')
        if not ((proc.stdout or '') + (proc.stderr or '')).strip():
            print(f'chock: blocked by {_chock_Path(guard).name} (guard gave no reason)', file=sys.stderr)
        return True
    if proc.returncode != 0:
        detail = (proc.stderr or proc.stdout or '').strip().splitlines()
        print(f'chock: guard exited {proc.returncode}, not checked' + (f': {detail[0][:120]}' if detail else ''), file=sys.stderr)
        return None
    return False

def log_outcome(guard: _chock_Path, tool: str, blocked: bool) -> None:
    """Append one outcome record. Best effort: never raises, never changes the verdict.

    Deliberately records NO command and no guard output. The command is the scanned content
    here, and commands routinely carry bearer tokens and passwords -- writing them to a
    plaintext file on every Bash call would create the exposure the secret policies exist to
    prevent. Which policy, which tool, and allow-or-block is the whole useful signal.
    """
    try:
        if _chock_os.environ.get(GATE_LOG_ENV) == '0':
            return
        guard = guard.resolve()
        if guard.parent.name != 'implementations':
            return
        artifact_root = None
        for parent in guard.parents:
            if (parent / '.chock').is_dir():
                artifact_root = parent / '.chock'
                break
        if artifact_root is None:
            return
        log_dir = artifact_root / 'log'
        log_dir.mkdir(parents=True, exist_ok=True)
        log_path = log_dir / 'gate-events.jsonl'
        if log_path.exists() and log_path.stat().st_size > _LOG_MAX_BYTES:
            log_path.replace(log_dir / 'gate-events.1.jsonl')
        import json
        record = {'ts': _chock_datetime.now(_chock_timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'), 'policy_id': guard.parent.parent.name, 'surface': 'pre-tool-use', 'event': 'tool_use', 'kind': guard.stem, 'tool': tool, 'verdict': 'block' if blocked else 'allow'}
        with log_path.open('a', encoding='utf-8') as fh:
            fh.write(json.dumps(record, ensure_ascii=False) + '\n')
    except Exception:
        return

def evaluate(argv: list[str], command: str, tool: str='') -> str | None:
    """Run the guard named on `argv` (`--guard <path>`) against `command`.

    Returns the deny reason when the guard reports a violation, None on allow (including
    every "not checked" case -- the guard's own stderr already explains those). The one
    caller-facing entry point `gate.runtime_bundle`'s spliced handler uses: locate the
    guard, run it, log the outcome, word the verdict.
    """
    guard = guard_path_from_argv(argv)
    if guard is None or not guard.exists():
        return None
    blocked = run_guard(guard, command)
    if blocked is not None:
        log_outcome(guard, tool, blocked)
    return f'Blocked by chock policy: {guard.stem}' if blocked else None


def handle(event):
    if event.event == "pre_tool" and event.command:
        reason = evaluate(sys.argv[1:], event.command, event.tool or "")
        return Decision.deny(reason) if reason else None
    return None
# <<< agentseam handler <<<


def _coerce(result):
    if result is None:
        return Decision.allow()
    if isinstance(result, Decision):
        return result
    raise TypeError("handle() must return a Decision or None, got %r" % (type(result),))


def _read_payload(stream):
    # Decode bytes ourselves rather than trust the platform locale -- a BOM'd or non-UTF-8
    # stdin must not silently disable the gate. See agentseam.dispatch for the incident
    # this guards: a Windows console's cp1252 layer turning a UTF-8 BOM into three bytes
    # json cannot parse, with the hook allowing everything while claiming enforcement.
    buffer = getattr(stream, "buffer", None)
    if buffer is not None:
        return buffer.read().decode("utf-8-sig", errors="replace")
    return stream.read().lstrip("\ufeff")


def _emit(out, text):
    buffer = getattr(out, "buffer", None)
    if buffer is not None:
        buffer.write(text.encode("utf-8"))
        buffer.flush()
    else:
        out.write(text)
        out.flush()


def main(stdin=None, stdout=None, exit=True):
    """Read one payload from stdin, dispatch, emit the 'cursor' response, exit."""
    stream = stdin if stdin is not None else sys.stdin
    out = stdout if stdout is not None else sys.stdout
    try:
        raw = json.loads(_read_payload(stream))
    except Exception:
        # Malformed input is not the agent's fault to pay for: allow, stay silent.
        if exit:
            sys.exit(0)
        return 0
    event = parse(raw)
    if event.event == UNKNOWN:
        # A vendor event this adapter has no mapping for. handle() is not called: it
        # reasons about the canonical vocabulary, and handing it something outside that
        # vocabulary invites a decision made on a false premise.
        if exit:
            sys.exit(0)
        return 0
    decision = degrade(_coerce(handle(event)), event)
    text, code = respond(decision, event)
    if text:
        _emit(out, text)
    if exit:
        sys.exit(code)
    return code


if __name__ == "__main__":  # pragma: no cover
    main()

