#!/usr/bin/env bash
# Generated by Chock. Refuses shell commands that write to agent-config or vendored
# enforcement paths -- the agent must not hand-edit its own authority. Reads pass;
# `chock sync` passes (it writes through the tool, not shell editing). Best-effort
# and coarse by design: when in doubt it blocks, and the fix is a two-step command
# or a human-approved run carrying 'chock: approved-config-change'.
set -eu

full="$*"

# A human-approved change says so in the command itself, visibly.
case "$full" in
    *"chock: approved-config-change"*) exit 0 ;;
esac

# Write-indicators: in-place editors, movers, deleters, and shell redirection.
# Matched against the whole command line as well as individual tokens, because a
# `bash -c "..."` payload arrives as one argument.
has_writer=0
case "$full" in
    *"sed -i"*|*">"*) has_writer=1 ;;
esac
for arg in "$@"; do
    case "$arg" in
        tee|rm|mv|cp|chmod|truncate|patch) has_writer=1 ;;
    esac
done
if [[ "$has_writer" -eq 0 ]]; then
    exit 0
fi

protected=""
case "$full" in
    *AGENTS.md*|*CLAUDE.md*|*GEMINI.md*|*copilot-instructions.md*| \
    *.cursorrules*|*.windsurfrules*|*.aider.conf.yml*| \
    *.claude/settings*|*.mcp.json*| \
    *.chock/bin/*|*.chock/compiled/*|*.git/hooks/*)
        protected=yes
        ;;
esac

if [[ -n "$protected" ]]; then
    echo "BLOCKED: shell write touching agent config is not allowed -- an agent must not edit its own guardrails. Regenerate managed files with \`chock sync\`, or have a human approve by including 'chock: approved-config-change' in the command." >&2
    exit 1
fi

exit 0
