#!/usr/bin/env bash
# Generated by Chock. Refuses git commit commands whose message narrates the development
# process instead of describing the change. Scans inline -m/--message text and, when the
# file is readable, the message behind -F/--file. Best-effort guard: a deny-list of
# process-leak markers, deliberately narrow so a false block stays rare -- edit MARKERS
# below to fit your team's vocabulary; the content is yours.
set -eu

is_git_commit=0
saw_git=0
for arg in "$@"; do
    case "$arg" in
        git) saw_git=1 ;;
        commit) [[ "$saw_git" -eq 1 ]] && is_git_commit=1 ;;
    esac
done
if [[ "$is_git_commit" -eq 0 ]]; then
    exit 0
fi

# Marker phrases that describe the conversation rather than the change. Matched
# case-insensitively as substrings of the commit message.
MARKERS=(
    "user asked"
    "user asks"
    "user requested"
    "user said"
    "user wants"
    "the user's"
    "per the conversation"
    "per our conversation"
    "this conversation"
    "in this session"
    "session summary"
    "chat transcript"
    "maintainer decision"
    "maintainer asked"
    "as agreed with"
    "docs/internal/"
)

collect=""
expect_msg=0
expect_file=0
for arg in "$@"; do
    if [[ "$expect_msg" -eq 1 ]]; then
        collect="$collect $arg"
        expect_msg=0
        continue
    fi
    if [[ "$expect_file" -eq 1 ]]; then
        [[ -r "$arg" ]] && collect="$collect $(cat "$arg" 2>/dev/null || true)"
        expect_file=0
        continue
    fi
    case "$arg" in
        -m|--message) expect_msg=1 ;;
        --message=*) collect="$collect ${arg#--message=}" ;;
        -m?*) collect="$collect ${arg#-m}" ;;
        -F|--file) expect_file=1 ;;
        --file=*) f="${arg#--file=}"; [[ -r "$f" ]] && collect="$collect $(cat "$f" 2>/dev/null || true)" ;;
    esac
done

if [[ -z "${collect// /}" ]]; then
    exit 0  # no inline message (editor flow): nothing to scan here
fi

lower="$(printf '%s' "$collect" | tr '[:upper:]' '[:lower:]')"
for marker in "${MARKERS[@]}"; do
    if [[ "$lower" == *"$marker"* ]]; then
        echo "BLOCKED: commit message narrates the development process ('$marker'). Describe the change itself; keep conversations, plans and decision trails out of git history -- on a public repo every message is published forever. If this phrase is legitimate here, edit the MARKERS list in this guard." >&2
        exit 1
    fi
done

exit 0
