#!/usr/bin/env bash
# Generated by Chock. Gates MCP server configuration (Claude Code's .mcp.json) as protected
# content: a shell write is refused unless every mcpServers entry visible on the command line
# matches a name+source pair already on the allowlist below. The allowlist lives in THIS
# script, so a shell edit to it is refused the same way protect-agent-config refuses a shell
# edit to any policy guard source (.agents/policies/*/implementations/) -- unless the command
# carries the same 'chock: approved-config-change' marker.
set -eu

# The allowlist IS the policy: maintainer-approved MCP servers, one per line as
# "name<TAB>source", where source is the launch command and its args (space-joined, in
# order) or the url for a remote server. Matching is exact-string after trimming. Add your
# own; ships with the official MCP reference filesystem server as a worked example.
ALLOWED_MCP_SERVERS=$'filesystem\tnpx -y @modelcontextprotocol/server-filesystem'

MCP_CONFIG_PATH=".mcp.json"

full="${CHOCK_RAW_COMMAND-}"
if [ -z "$full" ]; then
    full="$*"
fi
[ -z "$full" ] && exit 0

# A human-approved change says so in the command itself, visibly.
case "$full" in
    *"chock: approved-config-change"*) exit 0 ;;
esac

# Normalize Windows backslash paths so a `.mcp.json` reference matches either separator.
norm="${full//\\//}"

# Whole-token raw writers (deleters/movers/editors), word-split with globbing disabled so a
# `bash -c "tee .mcp.json"` payload is reached and basename-normalized so a path-qualified
# interpreter still matches. Copied from protect-agent-config's own writer detection --
# same coarse, self-contained logic, not reinvented here.
_has_writer_token() {
    local tok
    set -f
    for tok in $1; do
        case "${tok##*/}" in
            tee|rm|mv|cp|chmod|truncate|patch|dd|ed|ex) set +f; return 0 ;;
        esac
    done
    set +f
    return 1
}
# Interpreters invoked in a writing form (python -c, perl -i, ...); order-independent within
# one command string, path-qualified interpreters included.
_interp_write() {
    local seen=0 tok
    set -f
    for tok in $1; do
        case "${tok##*/}" in
            python|python3|perl|ruby|node) seen=1 ;;
        esac
        case "$tok" in
            -c|-e|--eval|-i|--in-place|-i.*|-pi|-pi.*|-ni|-ne)
                if [ "$seen" -eq 1 ]; then set +f; return 0; fi ;;
        esac
    done
    set +f
    return 1
}

has_writer=0
case "$full" in
    *"sed -i"*|*"--in-place"*|*">"*) has_writer=1 ;;
esac
if _has_writer_token "$*" || _has_writer_token "${CHOCK_RAW_COMMAND:-}"; then
    has_writer=1
fi
if _interp_write "$*" || _interp_write "${CHOCK_RAW_COMMAND:-}"; then
    has_writer=1
fi
if [ "$has_writer" -eq 0 ]; then
    exit 0
fi

# Is the write target the allowlist itself? It lives in this script
# (implementations/verify-mcp-allowlist.sh), so protecting the file protects the allowlist.
case "$norm" in
    *verify-mcp-allowlist.sh*)
        echo "BLOCKED: shell write to the MCP server allowlist is not allowed -- it is protected content, the same way protect-agent-config protects every policy's guard source. Have a human approve by including 'chock: approved-config-change' in the command." >&2
        exit 1
        ;;
esac

# Not a write touching the MCP config path either? Nothing to guard.
case "$norm" in
    *"$MCP_CONFIG_PATH"*) ;;
    *) exit 0 ;;
esac

# Look up the allowlisted source for a server name; empty return + failure means unlisted.
_lookup_allowed_source() {
    local want="$1" name src
    while IFS=$'\t' read -r name src; do
        if [ "$name" = "$want" ]; then
            printf '%s' "$src"
            return 0
        fi
    done <<<"$ALLOWED_MCP_SERVERS"
    return 1
}

_trim() {
    local s="$1"
    s="${s#"${s%%[![:space:]]*}"}"
    s="${s%"${s##*[![:space:]]}"}"
    printf '%s' "$s"
}

# Scan the command line (heredoc bodies included -- they are part of CHOCK_RAW_COMMAND) for
# `"name": { ... }` server entries. Deliberately coarse: one level of nesting is assumed (an
# entry's own window runs up to the NEXT such marker, not to a brace-matched close), so a
# server object carrying its own nested object (an "env" map, say) can shift that boundary --
# rewrite the write in two steps or add the pragma-free path below to be safe on those.
remaining="$full"
found_any=0
bad=""
while [[ "$remaining" =~ \"([A-Za-z0-9_.@/-]+)\"[[:space:]]*:[[:space:]]*\{ ]]; do
    name="${BASH_REMATCH[1]}"
    whole="${BASH_REMATCH[0]}"
    after="${remaining#*"$whole"}"
    remaining="$after"
    [ "$name" = "mcpServers" ] && continue

    window="$after"
    if [[ "$window" =~ \"[A-Za-z0-9_.@/-]+\"[[:space:]]*:[[:space:]]*\{ ]]; then
        next="${BASH_REMATCH[0]}"
        window="${window%%"$next"*}"
    fi

    cmd=""
    [[ "$window" =~ \"command\"[[:space:]]*:[[:space:]]*\"([^\"]*)\" ]] && cmd="${BASH_REMATCH[1]}"
    url=""
    [[ "$window" =~ \"url\"[[:space:]]*:[[:space:]]*\"([^\"]*)\" ]] && url="${BASH_REMATCH[1]}"
    args=""
    if [[ "$window" =~ \"args\"[[:space:]]*:[[:space:]]*\[([^]]*)\] ]]; then
        args_rest="${BASH_REMATCH[1]}"
        args_parts=()
        while [[ "$args_rest" =~ \"([^\"]*)\" ]]; do
            args_parts+=("${BASH_REMATCH[1]}")
            args_rest="${args_rest#*"${BASH_REMATCH[0]}"}"
        done
        args="${args_parts[*]}"
    fi

    if [ -n "$cmd" ]; then
        source="$cmd${args:+ $args}"
    else
        source="$url"
    fi
    found_any=1

    allowed_source="$(_lookup_allowed_source "$name")" || {
        bad="'$name' is not on the allowlist"
        break
    }
    if [ "$(_trim "$source")" != "$(_trim "$allowed_source")" ]; then
        bad="'$name' is on the allowlist, but its command/args/url do not match the allowlisted entry"
        break
    fi
done

if [ -n "$bad" ]; then
    echo "BLOCKED: MCP server config change refused -- $bad. Add or fix the entry (name + exact source) in the allowlist at the top of implementations/verify-mcp-allowlist.sh via a human-approved 'chock: approved-config-change' edit." >&2
    exit 1
fi

# A write to .mcp.json with no server entry visible on the command line (an opaque sed -i
# pattern, say) cannot be checked against the allowlist -- fail closed rather than allow
# silently.
if [ "$found_any" -eq 0 ]; then
    echo "BLOCKED: this command writes $MCP_CONFIG_PATH but no server entry is visible on the command line to verify against the allowlist. Write the full content inline, or have a human approve with 'chock: approved-config-change'." >&2
    exit 1
fi

exit 0
